name: Chatbot Workflow

on:
  issues:
    types: [opened]  # O workflow será acionado quando um issue for aberto

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest  # Usaremos uma máquina virtual Linux para rodar o script

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Faz checkout do código do repositório

      - name: Set up Python
        uses: actions/setup-python@v2  # Configura a versão do Python
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests  # Instala a biblioteca de requisições

      - name: Run chatbot script
        run: |
          python3 chatbot.py  # Executa o script Python para interagir com a IA e postar no GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Passando o token do GitHub
          HUGGINGFACE_API_KEY: ${{ secrets.HF_API_KEY }}  # Passando a chave da Hugging Face
