name: Responder Issue com IA

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
      - name: Realizando requisição para a IA (Hugging Face)
        run: |
          # A mensagem que o bot precisa responder
          ISSUE_TITLE="${{ github.event.issue.title }}"

          # Requisição para Hugging Face (ou outro modelo de IA)
          RESPONSE=$(curl -s -X POST "https://api-inference.huggingface.co/models/gpt2" \
          -H "Authorization: Bearer ${{ secrets.HF_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d "{\"inputs\": \"$ISSUE_TITLE\"}" | jq -r '.[0].generated_text')

          echo "Resposta da IA: $RESPONSE"

          # Comentar o issue com a resposta gerada
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
            -d "{\"body\": \"$RESPONSE\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
